name:  OWASP Dependency-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout repo
        uses: actions/checkout@v3

      - name:  Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: backend-diary
          path: ./
          format: HTML
          out: reports
          args: >
            --scan ./ 
            --format HTML 
            --out reports 
            --failOnCVSS 7
            --enableExperimental
            --nvdApiKey ${{ secrets.NVD_API_KEY }}

      - name:  Upload report artifact
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html
